import { ArrowRight, Eye, HeartHandshake, PawPrint, SlidersHorizontal, Target } from 'lucide-react';
import { Reveal } from '@/components/landing/Reveal';

const benefits = [
  [Eye, 'Understand your options', 'See the realistic paths that fit the situation you shared.', 'Tailored guidance'],
  [Target, 'See what’s getting in the way', 'Make unclear constraints and blockers easier to understand.', 'Diagnose bottlenecks'],
  [SlidersHorizontal, 'Find the smallest changes that could help', 'Explore what would need to change before a path becomes possible.', 'Actionable shifts'],
  [HeartHandshake, 'Connect with trusted resources', 'Find carefully selected support for the next step you choose.', 'Vetted community care'],
] as const;

export const ValueProposition = () => <section id="what-we-help" className="scroll-mt-24 border-b border-[var(--border-warm)]/55 bg-[var(--cream)] py-16 sm:py-20" aria-labelledby="value-heading"><div className="mx-auto max-w-[1380px] px-5 sm:px-8 lg:px-12">
  <Reveal><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--forest)]">Clarity in hard moments</p><h2 id="value-heading" className="mt-2 font-serif text-3xl font-semibold leading-tight text-[#18382c] sm:text-[40px]">What Keep Them Home helps you understand</h2><span className="mx-auto mt-3 block h-0.5 w-12 bg-[var(--warm-sand)]" aria-hidden="true" /></div></Reveal>
  <div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon, title, copy, link], index) => <Reveal key={title} delay={index * 0.065}><article className="landing-card flex min-h-[245px] flex-col rounded-[20px] border border-[var(--border-warm)]/45 bg-white/75 p-6 shadow-[0_10px_28px_rgba(46,84,64,.05)]"><span className={`flex h-12 w-12 items-center justify-center rounded-full ${index % 2 ? 'bg-[var(--warm-sand)]/25' : 'bg-[var(--sage)]/25'}`}><Icon className={`h-6 w-6 ${index % 2 ? 'text-[#b47b5d]' : 'text-[var(--forest)]'}`} aria-hidden="true" /></span><h3 className="mt-5 font-serif text-[21px] font-semibold leading-[1.08] text-[#18382c]">{title}</h3><p className="mt-3 text-[15px] leading-[1.45] text-[var(--charcoal)]/75">{copy}</p><p className="mt-auto flex items-center pt-5 text-sm font-semibold text-[var(--forest)]">{link}<ArrowRight className="ml-1.5 h-3.5 w-3.5" aria-hidden="true" /></p></article></Reveal>)}</div>
</div></section>;

export const BrandMoment = ({ onStart }: { onStart: () => void }) => <>
  <section className="relative overflow-hidden bg-[#f0d7c1] py-10 sm:py-12"><div className="mx-auto grid max-w-[1380px] items-center gap-8 px-5 text-center sm:px-8 lg:grid-cols-[.75fr_1px_1.6fr_auto] lg:gap-14 lg:px-12 lg:text-left">
    <Reveal direction="left"><h2 aria-label="People and pets belong together." className="brand-script text-[38px] text-[#B97859]">People and pets<br />belong together.<span className="ml-2 inline-block">♡</span></h2></Reveal><span className="hidden h-20 bg-[#bc8c72]/55 lg:block" aria-hidden="true" />
    <Reveal><div className="text-center"><blockquote className="font-serif text-2xl font-semibold italic leading-[1.16] text-[#18382c] sm:text-3xl">“Sometimes staying together doesn’t require<br className="hidden xl:block" /> everything to change. It requires finding the<br className="hidden xl:block" /> right thing to change first.”</blockquote><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--charcoal)]/70">Stronger communities. Happier pets. Brighter tomorrows.</p></div></Reveal><PawPrint className="mx-auto h-9 w-9 text-[#ca9878]" aria-hidden="true" />
  </div></section>
  <section className="relative overflow-hidden bg-[var(--forest)] py-11 text-[var(--cream)]"><div className="landing-organic landing-organic-left" aria-hidden="true" /><div className="landing-organic landing-organic-right" aria-hidden="true" /><Reveal><div className="relative mx-auto flex max-w-[1160px] flex-col items-center justify-between gap-8 px-5 text-center sm:px-8 lg:flex-row lg:text-left"><div><h2 className="font-serif text-3xl font-semibold sm:text-[40px]">See what’s possible for your pet.</h2><p className="mt-3 max-w-[580px] text-base leading-relaxed text-[var(--cream)]/88">Take a moment to describe your situation. We’ll help you untangle the obstacles and find practical ways to stay together.</p></div><div className="shrink-0 text-center"><button type="button" onClick={onStart} className="landing-cta group brand-focus inline-flex min-h-[50px] items-center rounded-full bg-[var(--cream)] px-9 text-base font-semibold text-[var(--forest)] shadow-lg hover:bg-white">Find options for my pet <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-[3px]" aria-hidden="true" /></button><p className="mt-3 text-xs text-[var(--cream)]/80">No judgment. No account required.</p></div></div></Reveal>
  </section>
</>;
