export const interventionCatalog = [
  {
    key: 'clarify_housing_restriction',
    title: 'Understand the exact housing restriction',
    description: 'Confirm whether the barrier comes from the lease, property policy, pet fees, breed restrictions, or another requirement.',
    supportedBarriers: ['housing'],
  },
  {
    key: 'address_housing_cost',
    title: 'Address the immediate housing cost',
    description: 'Look for assistance that may help with a pet deposit, fee, rent, utilities, or another housing expense.',
    supportedBarriers: ['housing'],
  },
  {
    key: 'search_pet_friendly_housing',
    title: 'Search for pet-friendly housing',
    description: 'Use verified guidance and directories to focus a housing search on rentals that can work for you and your pet.',
    supportedBarriers: ['housing'],
  },
  {
    key: 'seek_temporary_care_bridge',
    title: 'Consider a temporary care bridge',
    description: 'Explore whether short-term care could create time to resolve the housing situation without immediately pursuing permanent surrender.',
    supportedBarriers: ['housing'],
  },
  {
    key: 'explore_general_pet_support',
    title: 'Explore broader pet support',
    description: 'Check verified community directories for other practical support that may reduce pressure on the household.',
    supportedBarriers: ['housing'],
  },
  { key: 'behavior_management_plan', title: 'Build a safe behavior-management plan', description: 'Use management, routine, and environment changes without assuming the behavior is safe or diagnosed.', supportedBarriers: ['behavior'] },
  { key: 'behavior_separation_support', title: 'Explore safe short-term separation support', description: 'Check appropriate temporary separation options while qualified help is arranged.', supportedBarriers: ['behavior'] },
  { key: 'qualified_behavior_support', title: 'Find qualified behavior support', description: 'Explore qualified training, behavior consulting, or veterinary behavior support as appropriate.', supportedBarriers: ['behavior'] },
  { key: 'lower_cost_service', title: 'Find an appropriate lower-cost option', description: 'Compare verified lower-cost services or support without assuming eligibility or availability.', supportedBarriers: ['cost'] },
  { key: 'financial_assistance_search', title: 'Search for short-term financial support', description: 'Use established directories to explore assistance for the immediate pet-related expense.', supportedBarriers: ['cost'] },
  { key: 'lower_cost_veterinary_search', title: 'Search for appropriate veterinary care', description: 'Explore lower-cost or accessible veterinary providers without replacing professional care.', supportedBarriers: ['medical'] },
  { key: 'veterinary_support_navigation', title: 'Navigate veterinary support options', description: 'Explore care and financial-support options for the short-term gap.', supportedBarriers: ['medical'] },
  { key: 'veterinary_transport_support', title: 'Explore treatment-burden support', description: 'Look for transport, routine, or caregiving support connected to professional care.', supportedBarriers: ['medical'] },
  { key: 'temporary_caregiver', title: 'Explore appropriate temporary caregiving', description: 'Check short-term care options that keep reunification in view.', supportedBarriers: ['temporary_crisis', 'circumstances'] },
  { key: 'trusted_network_support', title: 'Ask a trusted support network', description: 'Identify a trusted person who may be able to help during the disruption.', supportedBarriers: ['temporary_crisis'] },
  { key: 'emergency_pet_support', title: 'Explore short-term crisis support', description: 'Search for practical support that may allow owner and pet to remain together.', supportedBarriers: ['temporary_crisis'] },
  { key: 'routine_modification', title: 'Restructure the essential care routine', description: 'Change how essential pet-care tasks fit into the available time.', supportedBarriers: ['time_capacity'] },
  { key: 'shared_caregiving', title: 'Explore shared caregiving', description: 'Identify an appropriate helper for specific care tasks.', supportedBarriers: ['time_capacity'] },
  { key: 'household_transition_planning', title: 'Plan a pet-inclusive household transition', description: 'Identify adaptations that may keep the pet included through the life change.', supportedBarriers: ['circumstances'] },
  { key: 'housing_transition_support', title: 'Explore a pet-inclusive living arrangement', description: 'Plan housing or household changes that continue to include the pet.', supportedBarriers: ['circumstances'] },
] as const;

export type InterventionKey = typeof interventionCatalog[number]['key'];

export const interventionResourceSlugs: Record<InterventionKey, string[]> = {
  clarify_housing_restriction: [
    'humane-world-renters',
    'aspca-housing-renters',
    'best-friends-rentals-guide',
  ],
  address_housing_cost: [
    'united-way-211-housing',
    'arizona-humane-bridge-gap',
    'pets-findhelp',
  ],
  search_pet_friendly_housing: [
    'best-friends-rentals-guide',
    'humane-world-renters',
    'aspca-housing-renters',
  ],
  seek_temporary_care_bridge: [
    'pet-help-finder',
    'safe-havens-for-pets',
    'arizona-humane-bridge-gap',
  ],
  explore_general_pet_support: [
    'pets-findhelp',
    'pet-help-finder',
    'united-way-211-housing',
  ],
  behavior_management_plan: ['pets-findhelp', 'pet-help-finder'],
  behavior_separation_support: ['pet-help-finder', 'pets-findhelp'],
  qualified_behavior_support: ['pets-findhelp', 'pet-help-finder'],
  lower_cost_service: ['pets-findhelp', 'pet-help-finder', 'united-way-211-housing'],
  financial_assistance_search: ['pets-findhelp', 'pet-help-finder', 'united-way-211-housing'],
  lower_cost_veterinary_search: ['pet-help-finder', 'pets-findhelp'],
  veterinary_support_navigation: ['pet-help-finder', 'pets-findhelp'],
  veterinary_transport_support: ['pets-findhelp', 'pet-help-finder'],
  temporary_caregiver: ['pet-help-finder', 'safe-havens-for-pets', 'pets-findhelp'],
  trusted_network_support: ['pet-help-finder', 'pets-findhelp'],
  emergency_pet_support: ['pet-help-finder', 'safe-havens-for-pets', 'pets-findhelp'],
  routine_modification: ['pets-findhelp', 'pet-help-finder'],
  shared_caregiving: ['pets-findhelp', 'pet-help-finder'],
  household_transition_planning: ['pets-findhelp', 'pet-help-finder'],
  housing_transition_support: ['best-friends-rentals-guide', 'humane-world-renters', 'pets-findhelp'],
};
