import { useEffect, useMemo, useState } from 'react';
import { actionCatalog } from '../../../server/actions/catalog';
import { solveRetentionPaths } from '../../../server/retention-paths/solver';
import type { NormalizedHousingCase } from '../../../server/retention-paths/domain';
import { Button } from '@/components/ui/button';
import { caseApi, type CaseAction, type CaseActionStatus, type CaseEvent, type NotPossibleReason, type RetentionPathResult } from '@/lib/case-api';

interface Props { backendCaseId?: string; path: RetentionPathResult; facts: NormalizedHousingCase; onRecompute: (paths: RetentionPathResult[]) => void; onCheckIn?: () => void; }
const statuses: Array<{ value: CaseActionStatus; label: string }> = [{ value: 'PLANNED', label: 'Planned' }, { value: 'IN_PROGRESS', label: 'In progress' }, { value: 'COMPLETED', label: 'Completed' }, { value: 'NOT_POSSIBLE', label: 'Not possible' }];
const reasons: Array<{ value: NotPossibleReason; label: string }> = [{ value: 'COST', label: 'Too expensive' }, { value: 'NO_AVAILABILITY', label: 'No availability' }, { value: 'NOT_ELIGIBLE', label: 'Not eligible' }, { value: 'NO_RESPONSE', label: 'No response' }, { value: 'TIME', label: 'Not enough time' }, { value: 'TRANSPORTATION', label: 'Transportation' }, { value: 'SAFETY', label: 'Safety concern' }, { value: 'HOUSING', label: 'Housing restriction' }, { value: 'HOUSEHOLD', label: 'Household issue' }, { value: 'OTHER', label: 'Other' }];

export default function NextSteps({ backendCaseId, path, facts, onRecompute, onCheckIn }: Props) {
  const recommendation = useMemo(() => actionCatalog.find(({ pathKey }) => pathKey === path.key), [path.key]);
  const [actions, setActions] = useState<CaseAction[]>([]); const [events, setEvents] = useState<CaseEvent[]>([]); const [reason, setReason] = useState<NotPossibleReason>('COST'); const [note, setNote] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { if (!backendCaseId) return; let active = true; void caseApi.getActions(backendCaseId).then(({ actions: saved, events: history }) => { if (active) { setActions(saved); setEvents(history); } }).catch(() => undefined); return () => { active = false; }; }, [backendCaseId]);
  const tracked = actions.find((action) => action.pathKey === path.key && action.actionKey === recommendation?.key);
  const localAction = (): CaseAction => { const stamp = new Date().toISOString(); return { id: `local-${recommendation!.key}`, caseId: 'temporary', pathKey: path.key, actionKey: recommendation!.key, interventionKey: recommendation!.interventionKey ?? null, relatedFact: recommendation!.relatedFact, title: recommendation!.title, description: recommendation!.description, status: 'PLANNED', notPossibleReason: null, resultNote: null, outcomeKey: null, createdAt: stamp, updatedAt: stamp, completedAt: null }; };
  const localEvent = (eventType: string, title: string, actionId: string): CaseEvent => ({ id: `local-event-${crypto.randomUUID()}`, caseId: 'temporary', actionId, eventType, eventData: { title }, createdAt: new Date().toISOString() });
  const add = async () => { if (!recommendation) return; const action = backendCaseId ? await caseApi.addAction(backendCaseId, path.key, recommendation.key) : localAction(); setActions((current) => [...current.filter(({ id }) => id !== action.id), action]); if (!backendCaseId) setEvents((current) => [...current, localEvent('ACTION_ADDED', `Added “${action.title}”`, action.id)]); };
  const update = async (action: CaseAction, status: CaseActionStatus, selectedReason = reason) => { const input = { status, notPossibleReason: status === 'NOT_POSSIBLE' ? selectedReason : null, resultNote: note.trim() || null }; const updated = backendCaseId ? await caseApi.updateAction(backendCaseId, action.id, input) : { ...action, ...input, updatedAt: new Date().toISOString(), completedAt: status === 'COMPLETED' ? new Date().toISOString() : null }; setActions((current) => current.map((item) => item.id === action.id ? updated : item)); if (!backendCaseId) setEvents((current) => [...current, localEvent('ACTION_STATUS_CHANGED', `Marked “${action.title}” ${statuses.find(({ value }) => value === status)?.label.toLowerCase()}`, action.id)]); setNotice(status === 'COMPLETED' ? 'Action completed. Tell us what happened before any case fact changes.' : status === 'NOT_POSSIBLE' ? 'The underlying facts and path status have not changed.' : 'Action status updated.'); };
  const confirmOutcome = async (action: CaseAction, outcomeKey: string) => { const outcome = recommendation?.outcomes.find(({ key }) => key === outcomeKey); if (!outcome || !recommendation) return; if (backendCaseId) { const result = await caseApi.recordActionOutcome(backendCaseId, action.id, outcomeKey, note.trim() || undefined); setActions((current) => current.map((item) => item.id === action.id ? result.action : item)); onRecompute(result.paths); setNotice(result.changedFact ? 'Your options changed after the fact you confirmed.' : 'Result recorded. No case fact changed.'); return; } setActions((current) => current.map((item) => item.id === action.id ? { ...item, outcomeKey, resultNote: note.trim() || null } : item)); setEvents((current) => [...current, localEvent('ACTION_OUTCOME_RECORDED', outcome.label, action.id)]); if (outcome.factValue !== undefined) { const changed = { ...facts, constraints: { ...facts.constraints, [recommendation.relatedFact]: outcome.factValue } }; onRecompute(solveRetentionPaths(changed).map((item) => ({ ...item, steps: item.steps.map((step) => ({ ...step, resources: [] })) }))); setNotice('Your options changed after the fact you confirmed.'); } else setNotice('Result recorded. No case fact changed.'); };
  if (!recommendation) return null;
  return <section className="mt-9 border-t border-[var(--border-warm)] pt-8" aria-labelledby="next-steps-heading"><h3 id="next-steps-heading" className="font-serif text-3xl text-[var(--forest)]">Next steps</h3><p className="mt-2 text-[var(--text-muted)]">Choose actions you want to work on. Completing an action does not change your case facts.</p>
    {!tracked ? <article className="mt-5 rounded-xl border border-[var(--sage)] bg-white p-5"><h4 className="text-lg font-bold text-[var(--forest)]">{recommendation.title}</h4><p className="mt-2 text-sm text-[var(--text-muted)]">{recommendation.description}</p><Button type="button" onClick={() => void add()} className="mt-4 bg-[var(--forest)] text-white">Add to my plan</Button></article> : <article className="mt-5 rounded-xl border border-[var(--sage)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-bold text-[var(--forest)]">{tracked.title}</h4><p className="mt-2 text-sm text-[var(--text-muted)]">{tracked.description}</p><p className="mt-2 text-xs text-[var(--text-muted)]">Related blocker: {path.blockers.find(({ field }) => field === tracked.relatedFact)?.label ?? 'Path requirement'} · Updated {new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(tracked.updatedAt))}</p></div><span className="rounded-full bg-[var(--surface-soft)] px-3 py-1 text-sm font-semibold">{statuses.find(({ value }) => value === tracked.status)?.label}</span></div><fieldset className="mt-5"><legend className="text-sm font-bold">Update status</legend><div className="mt-2 flex flex-wrap gap-2">{statuses.map((status) => <Button key={status.value} type="button" variant="outline" aria-pressed={tracked.status === status.value} onClick={() => void update(tracked, status.value)}>{status.label}</Button>)}</div></fieldset>
      {(tracked.status === 'NOT_POSSIBLE' || tracked.status === 'COMPLETED') && <label className="mt-4 block text-sm font-bold">Optional note<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={300} rows={2} className="mt-2 block w-full rounded-md border bg-white p-3 font-normal" /></label>}
      {tracked.status === 'NOT_POSSIBLE' && <label className="mt-4 block text-sm font-bold">What got in the way?<select aria-label="What got in the way?" value={tracked.notPossibleReason ?? reason} onChange={(event) => { const value = event.target.value as NotPossibleReason; setReason(value); void update(tracked, 'NOT_POSSIBLE', value); }} className="mt-2 block w-full rounded-md border bg-white p-3 font-normal">{reasons.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><span className="mt-3 block font-normal text-[var(--text-muted)]">Another way to address this may be available through the other paths or resources below.</span></label>}
      {tracked.status === 'COMPLETED' && !tracked.outcomeKey && <fieldset className="mt-5"><legend className="font-bold">What happened?</legend><div className="mt-3 grid gap-2">{recommendation.outcomes.map((outcome) => <Button key={outcome.key} type="button" variant="outline" onClick={() => void confirmOutcome(tracked, outcome.key)} className="justify-start whitespace-normal text-left">{outcome.label}</Button>)}</div></fieldset>}
      {path.steps.flatMap((step) => step.resources).length > 0 && <details className="mt-5"><summary className="cursor-pointer text-sm font-bold text-[var(--forest)]">Helpful resources</summary><ul className="mt-2 space-y-2 text-sm">{path.steps.flatMap((step) => step.resources).map((resource) => <li key={resource.id}><a href={resource.url} target="_blank" rel="noreferrer" className="underline">{resource.name}</a></li>)}</ul></details>}
    </article>}{notice && <p className="mt-4 rounded-lg bg-[var(--surface-soft)] p-3 text-sm font-semibold" aria-live="polite">{notice}</p>}{tracked?.status === 'COMPLETED' && onCheckIn && <Button type="button" variant="outline" onClick={onCheckIn} className="mt-4 border-[var(--forest)] text-[var(--forest)]">How are things now?</Button>}{events.length > 0 && <details className="mt-5"><summary className="cursor-pointer font-bold text-[var(--forest)]">Plan history</summary><ol className="mt-3 space-y-2 text-sm text-[var(--text-muted)]">{events.map((event) => <li key={event.id}>{new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(event.createdAt))} — {event.eventData.title ?? event.eventType.replace(/_/g, ' ').toLowerCase()}</li>)}</ol></details>}</section>;
}
